server: 
    port: 80
    context-path: /

spring: 
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_film
      username: root
      password: 
   jpa: 
      hibernate:
        ddl-auto: update
      show-sql: true
   thymeleaf:
       cache: false
imageFilePath: E://KFTools/eclipse4.6/workspace/Film/src/main/webapp/static/filmImage/ 